force-app/main/default/objects/Account/fields/Region_Location__c.field-meta.xml
<CustomField>
    <fullName>Region_Location__c</fullName>
    <description>Where is the region location of the applicant.</description>
    <label>Region Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region_Location_GLOBAL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Work_Category__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Work_Category__c</fullName>
    <description>The type of work category the business is in.</description>
    <inlineHelpText>Select the work category the applicant&apos;s business is in.</inlineHelpText>
    <label>Type of Work - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Work_Category_GLOBAL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Region_Location__c.field-meta.xml
<CustomField>
    <fullName>Region_Location__c</fullName>
    <label>Region Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region_Location_GLOBAL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount_Asked__c.field-meta.xml
<CustomField>
    <fullName>Amount_Asked__c</fullName>
    <label>Amount Asked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>The day the contract expires.</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>The day the contract starts.</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Industry_Name__c.field-meta.xml
<CustomField>
    <fullName>Industry_Name__c</fullName>
    <description>The industry name displayed for the NAICS Code.</description>
    <formula>Industry_NAICS_Code__r.Industry_Name__c</formula>
    <label>Industry Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region_Location__c.field-meta.xml
<CustomField>
    <fullName>Region_Location__c</fullName>
    <label>Region Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region_Location_GLOBAL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Remaining_Days_Contract_Expires__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Days_Contract_Expires__c</fullName>
    <description>Calculates the contract expiration day.</description>
    <formula>IF(Contract_End_Date__c - TODAY() &gt; 0, Contract_End_Date__c - TODAY(), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Days: Contract Expires</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Work_Category__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Work_Category__c</fullName>
    <label>Type of Work - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Work_Category_GLOBAL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Region_Location_GLOBAL.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>Northeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>Southwest</fullName>
    </customValue>
    <customValue>
        <fullName>West</fullName>
    </customValue>
    <masterLabel>Region Location (GLOBAL)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type_of_Work_Category_GLOBAL.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Advanced Materials and Manufacturing Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Bioenergy Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Buildings</fullName>
    </customValue>
    <customValue>
        <fullName>Geothermal Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Hydrogen and Fuel Cell Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial Efficiency and Decarbonization</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Energy Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Water Power Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Wind Energy Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Vehicle Technologies</fullName>
    </customValue>
    <masterLabel>Type of Work - Category (GLOBAL)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/applicationCheckerController.cls
public with sharing class applicationCheckerController {

    @AuraEnabled(cacheable=true)
    public static User getAccountId() {
        User currUserAccount = [SELECT Contact.AccountId, Contact.Account.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        return currUserAccount;
        //return [SELECT Id, Name FROM Account WHERE Id = :currUserAccount.AccountId LIMIT 1];
    }


    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getRelatedOpportunity(Id accountId) {
        try {
            return [SELECT Id, Name, Description, Type, StageName, 	Type_of_Work_Category__c, Region_Location__c, 
                            Likelihood_of_Acceptance__c, Industry_Name__c, Grant_Given__r.Name, Amount_Asked__c, Amount,
                            Contract_Start_Date__c, Contract_End_Date__c, Remaining_Days_Contract_Expires__c, 
                            Compliance_Status__c, Progress_Note__c, Termination_Date__c, Reason_for_Termination__c
                    FROM Opportunity 
                    WHERE AccountId = :accountId];
        } catch (Exception e) {
            throw new AuraHandledException('Failed to fetch related materials: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getStage(Id accountId) {
        try {
            return [SELECT StageName
                    FROM Opportunity 
                    WHERE AccountId = :accountId];
        } catch (Exception e) {
            throw new AuraHandledException('Failed to fetch related materials: ' + e.getMessage());
        }
    }
       

    @AuraEnabled(cacheable=true)
    public static List<Case> getRelatedCases(Id accountId) {
        try {
            return [SELECT Id, CaseNumber, Subject, Description, Status
                    FROM Case 
                    WHERE AccountId = :accountId];
        } catch (Exception e) {
            throw new AuraHandledException('Failed to fetch related materials: ' + e.getMessage());
        }
    }


    @AuraEnabled(cacheable=true)
    public static List<Task> getTasks(Id opportunityId) {
        Set<String> filter = new Set<String>();
        filter.add('%Call%');
        filter.add('%Send%');
        //filter.add('%Email%');
        filter.add('%Other%');

        return [SELECT Id, Subject, ActivityDate, Description 
                FROM Task 
                WHERE WhatId = :opportunityId  /// AND Subject LIKE :filter
                ORDER BY ActivityDate DESC];
    }

    @AuraEnabled(cacheable=true)
    public static List<Event> getEvents(Id opportunityId) {
        return [SELECT Id, Subject, ActivityDate, Description 
                FROM Event 
                WHERE WhatId = :opportunityId 
                ORDER BY ActivityDate DESC];
    }

    @AuraEnabled(cacheable=true)
    public static List<EmailMessage> getEmails(Id opportunityId) {
        return [SELECT Id, Subject, CreatedDate, TextBody 
                FROM EmailMessage 
                WHERE RelatedToId = :opportunityId 
                ORDER BY CreatedDate DESC];
    }

    @AuraEnabled(cacheable=true)
    public static List<Task> getCalls(Id opportunityId) {
        return [SELECT Id, Subject, ActivityDate, Description 
                FROM Task 
                WHERE WhatId = :opportunityId AND Subject LIKE '%Call%' 
                ORDER BY ActivityDate DESC];
    }



    @AuraEnabled(cacheable=true)
    public static List<ContentDocumentLinkWrapper> getNotesAndAttachments(Id opportunityId) {
        List<ContentDocumentLinkWrapper> notesAndAttachments = new List<ContentDocumentLinkWrapper>();

        // Fetching attachments (using the ContentDocumentLink object)
        List<ContentDocumentLink> attachments = [SELECT ContentDocument.Title, ContentDocumentId, ContentDocument.CreatedDate, ContentDocument.FileType
                                                FROM ContentDocumentLink
                                                WHERE LinkedEntityId = :opportunityId
        ];
        for (ContentDocumentLink attachment : attachments) {
            notesAndAttachments.add(new ContentDocumentLinkWrapper(
                attachment.ContentDocumentId,
                attachment.ContentDocument.Title,
                attachment.ContentDocument.CreatedDate,
                attachment.ContentDocument.FileType
            ));
        }

        return notesAndAttachments;
    }


    @AuraEnabled
    public static void linkContentDocument(Id opportunityId, Id contentDocumentId) {
        ContentDocumentLink attach = new ContentDocumentLink();
        attach.LinkedEntityId = opportunityId;
        attach.ContentDocumentId = contentDocumentId;
        attach.ShareType = 'V';
        attach.Visibility = 'AllUsers';
        insert attach;
    }

    public class ContentDocumentLinkWrapper {
        @AuraEnabled public Id Id { get; set; }
        @AuraEnabled public String Title { get; set; }
        @AuraEnabled public DateTime CreatedDate { get; set; }
        @AuraEnabled public String Type { get; set; }

        public ContentDocumentLinkWrapper(Id id, String title, DateTime createdDate, String contentType) {
            this.Id = id;
            this.Title = title;
            this.CreatedDate = createdDate;
            this.Type = contentType;
        }
    }
    
    

}